### ISSUE TITLE
Add a "requirements" section

### ISSUE THREAD

**Issue by gunnarmorling** [jetty-project/annotation-discovery#1]
Hey, came across your thread on discuss - I think it's a very valuable goal. Perhaps a "requirements" section should be added?

* Retrieve annotation information without loading classes (goes without saying, but also perhaps useful to add as non-viable alternative)
* Retrieve annotation information by looking up from meta-annotations (directly or even indirectly present)
* ...

**Comment by gregw** [comment]
\o/ first issue raised and fixed :)
