### ISSUE TITLE
Consider supporting implementation discovery (or other dynamic criteria)

### ISSUE THREAD

**Issue by kaqqao** [jetty-project/annotation-discovery#3]
It is often needed to discover classes implementing an interface or inheriting a class, for much the same reasons like scanning for annotations. Most annotation discovery code used presently (in Reflections, Spring etc) supports this use-case already and existing frameworks may depend on it.
Since the hard part of the problem is identical, it may be worth considering supporting this search criteria as a part of the standard. Further more, it might be beneficial to allow dynamic search criteria to be defined.

**Comment by gregw** [comment]
Good idea, as it suffers same issues with MR jars and modules.  Added a requirement
