### ISSUE TITLE
Some pointers

### ISSUE THREAD

**Issue by lukehutch** [jetty-project/annotation-discovery#4]
@gregw I'm glad you were spearheading this initiative to add annotation discovery or indexing to JPMS. Sad to see the conversation die out on the openjdk discuss mailing list.

I see that you were asking about module scanning too:

http://mail.openjdk.java.net/pipermail/jigsaw-dev/2017-September/013182.html

It took me a long time to figure out how to properly scan modules, so I wanted to make sure you saw my writeup on it here:

https://stackoverflow.com/questions/41932635/scanning-classpath-modulepath-in-runtime-in-java-9/45612376#45612376

I rewrote this to use reflection, and integrated it into ClassGraph, which (at least until the JPMS supports annotation discovery natively) may solve Jetty's need for scanning:

https://github.com/classgraph/classgraph

Feel free to close this, it's not an actual bug report, I just wanted to make you aware of the two previous links above, since it was so hard to figure this out, and you were asking all the same questions I was!

**Comment by sbordet** [comment]
@lukehutch nice work!

Current status with JPMS support is on eclipse/jetty.project#2191.
For 9.4.x the support will be via `Automatic-Module-Name`. The implementation is on branch `jetty-9.4.x-2191-jpms_automatic_module_name`.

For 10.0.x we are thinking of requiring JDK 11, so proper `module-info.java` and JDK 9 Module APIs will be used.

**Comment by PavelTurk** [comment]
@lukehutch Could you show an example of using classgraph how to scan JPMS module to find all resources with some extension? I mean I have `Module myModule` and I want to scan `myModule`.

**Comment by lukehutch** [comment]
Yes, an example is here:

https://github.com/classgraph/classgraph/wiki/Code-examples#2-reading-resource-files

To scan only a specific module, just call `.whitelistModule(myModule)` before `.scan()`. You could also disable directory and jar scanning if you only want to scan modules.

**Comment by PavelTurk** [comment]
@lukehutch Thank you for your answer. But this code scans all modules, but I am asking about solution to scan only `one` specific module - when I have the path|name|reference to this module. Is it possible?

**Comment by lukehutch** [comment]
@PashaTurok yes -- to turn the suggestions in my previous comment into code, you would have:

```java
Map<String, String> pathToFileContent = new HashMap<>();
try (ScanResult scanResult =
        new ClassGraph()
            .whitelistModule(myModule)    // Module name, e.g. "my.module"
            .whitelistPaths("META-INF/config")   // If needed
            .disableJarScanning()   // If you only want to scan modules and not jars
            .disableDirScanning()   // If you only want to scan modules and not dirs
            .scan()) {
    scanResult
        .getResourcesWithExtension("xml")
        // could also add ".filter(resource -> predicate(resource))" here
        .forEachByteArray((Resource res, byte[] fileContent) -> {
            pathToFileContent.put(res.getPath(), new String(fileContent));
        });
}
```

If a module is whitelisted, *only* that module is scanned. If no module is whitelisted, *all* modules are scanned. (Same for whitelisted paths etc.)

**Comment by PavelTurk** [comment]
@lukehutch Oh, thank you. That is great. Could you also say the following. Lets suppose we have three JPMS layers - boot, layerA (child of the boot), layerB (child of the boot). And we use ClassGraph in layerA. What layers will be scanned ? I mean when `.whitelistModule(myModule)` is not used.

About your code - my fault. I clicked the link you provided and didn't read your comment.

**Comment by lukehutch** [comment]
@PashaTurok Currently ClassGraph scans all modules that are visible in the context from which it is invoked. So if you invoke ClassGraph from layerA, it will scan layerA and boot (unless you specifically whitelist only layerA, so that boot is not scanned). Neither the invoking code nor ClassGraph has any idea of layerB's existence if the code is running in layerA, and in fact there is absolutely no way to even access layerB, due to strong encapsulation, and the fact that the layer API can query only parent layers, not sibling layers.

**Comment by PavelTurk** [comment]
@lukehutch Yes, I know about sibling and even asked question about it here https://stackoverflow.com/questions/52314505/how-to-get-list-of-all-jpms-layers . I thought that maybe you found also solution and to this problem.

**Comment by PavelTurk** [comment]
@lukehutch One more question - but if I am in layerA and having reference to layerB, can I make ClassGraph scan layerB? This is very important for this issue https://github.com/eclipse/jetty.project/issues/2895

**Comment by lukehutch** [comment]
> Yes, I know about sibling and even asked question about it here https://stackoverflow.com/questions/52314505/how-to-get-list-of-all-jpms-layers . I thought that maybe you found also solution and to this problem.

One of your responses saying this is not possible was Alan Bateman himself -- he actually built this system in the JDK, as far as I know, so you can trust that his answer is the correct one. This is not possible with the current API (and this is currently by design).

It's nice that he asked though what your usecase is. I guess that means he would be open to understanding reasons to be able to scan all modules in the heap. However, in my own interactions with him, asking similar questions (about trying to discover all modules, not just parent and ancestor modules), I get the feeling that the JDK team feels like the current design is the right one.

And actually, discovering non-ancestor modules really is not useful, because any scanning code that were to discover classes in non-ancestral modules would have no chance of actually interacting with any of the non-ancestral-module classes that were discovered. It might still be useful for discovering resource files in non-ancestral modules, but you'd have to make a strong case to Alan before he would consider changing it.

Right now there is no way to add a custom `ModuleLayer` to ClassGraph, but I could add a `ClassGraph#addModuleLayer(ModuleLayer customModuleLayer)` method. This makes sense, since there is a `ClassGraph#addClassLoader(ClassLoader customClassLoader)` method.

**Comment by PavelTurk** [comment]
If you add `ClassGraph#addModuleLayer(ModuleLayer customModuleLayer) method` it will be nice. It would help us a lot.

**Comment by lukehutch** [comment]
@PashaTurok done, please test the master version of ClassGraph to make sure it does what you need, then I will push out a release.

**Comment by PavelTurk** [comment]
@lukehutch Thank you. But with testing we must a little wait until jetty can allow to deploy war in separate layer. I hope it will be soon.

**Comment by kaqqao** [comment]
Shouldn't this discussion take place in ClassGraph and not Jetty?

Btw, you might want to know about this amazing hack I picked up from Rafael Winterhalter.

```java
Field field = Class.class.getDeclaredField("module");
setAccesibleViaPutBoolean(field);
field.put(MyKlass.class, Object.class.getModule());
// Now your class is part of java.base
// all credit @jmichaelras
```
Where `setAccesibleViaPutBoolean` I believe refers to using
> `sun.misc.Unsafe::putBoolean` to write true to the override field of `AccessibleObject`

A total hack, and probably won't work forever, but gives you a way to jump the module barrier. An interesting experiment, at least.

**Comment by lukehutch** [comment]
@kaqqao maybe the conversation should be over in ClassGraph, but right now only Jetty cares about scanning dynamically-created module layers. Either way, it made sense to add this method to ClassGraph, so it will be in the next release.

That's a cool trick to move anything you want into java.base, but what exactly can you do with that?

**Comment by PavelTurk** [comment]
@sbordet I did say that we can be the first and create reference implementation :)

**Comment by lukehutch** [comment]
@PashaTurok even if you want to wait to see if Jetty will go and allow your WAR module layer isolation change, please go ahead and test the new  `ClassGraph#addModuleLayer(ModuleLayer customModuleLayer)` method, since that should only take a second once you have built the ClassGraph jar (using mvn package).

**Comment by PavelTurk** [comment]
@lukehutch Ok. The following code I execute in custom layer, which is the child of boot layer:
       
        //FRAGMENT 1
        try (ScanResult scanResult = new ClassGraph().addModuleLayer(this.getClass().getModule().getLayer()).scan()) {
            scanResult
                .getResourcesWithExtension("MF")
                .forEach((Resource res) -> {
                    System.out.println("Found 1 :" + res.getURL());
                });
        }
       //FRAGMENT 2
        try (ScanResult scanResult = new ClassGraph().overrideModuleLayers(this.getClass().getModule().getLayer()).scan()) {
            scanResult
                .getResourcesWithExtension("MF")
                .forEach((Resource res) -> {
                    System.out.println("Found 2 :" + res.getURL());
                });
        }

I thought, that FRAGMENT 1 must show manifest files of jars that are both in boot layer and custom layer, and FRAGMENT 2 must show manifest files of jars that are only in custom layer. However, FRAGMENT 1 and FRAGMENT 2 give the same output. Is this my mistake?

**Comment by lukehutch** [comment]
@PashaTurok They give the same output because you are running the scanning code in the custom layer. You should get exactly the same result using just `new ClassGraph().scan()`. Since you are running in the custom layer, ClassGraph finds the custom layer on its own.

What you need to do is define the custom layer in a different layer, then running in that different layer, call one of those two fragments of code, but replace `this.getClass().getModule().getLayer()` with the reference to the custom layer (the one you're not running within).

That's the whole point of the methods I added -- to allow you to scan layers that are not visible to the running code, except as a `ModuleLayer` reference (i.e. dynamically-created module layers).

**Comment by PavelTurk** [comment]
@lukehutch Oh, I see. Thank you for your explanation. I think that it necessary to add switch - boolean includeParentLayers when we scan custom layer from custom layer. BTW why `ClassGraph addModuleLayer(Object moduleLayer)` but not `ClassGraph addModuleLayer(ModuleLayer moduleLayer)` ?

**Comment by lukehutch** [comment]
@PashaTurok The Javadoc explains the reason:

> (The parameter is of type `Object` for backwards compatibility with JDK 7 and JDK 8, but the argument should be of type `ModuleLayer`.)

There is a method `ClassGraph#ignoreParentClassLoaders()`, and I could add a method `ClassGraph#ignoreParentModuleLayers()`, but that is getting a bit exotic. Most of the time the only parent layer will be the boot layer, which contains system modules, and all system modules are ignored by default by ClassGraph, so they won't be scanned. You can also simply whitelist all the modules (or all the packages) in the custom module, which will mean any non-system modules in any parent or ancestor layers won't be scanned. Is that sufficient, or do you think ClassGraph still needs `ClassGraph#ignoreParentModuleLayers()`?

**Comment by PavelTurk** [comment]
@lukehutch 1)Why do you say that boot layer contains system modules? It can also contain custom modules that are added via module path. Can't it? 2)You say `Most of the time the only parent layer will be the boot layer`. Layers allow create layer tree, so there easily CAN be situations when parent != boot and making library we must consider this also. 3) I am sure that it is necessary to add ClassGraph#ignoreParentModuleLayers(). For example, I am in plugin layer and I need to scan only my own layer. The code will get crazy trying to understand what belongs to this layer and what doesn't.

**Comment by lukehutch** [comment]
On (1), I don't think so -- see here: https://docs.oracle.com/javase/9/docs/api/java/lang/ModuleLayer.html

> A Java virtual machine has at least one non-empty layer, the boot layer, that is created when the Java virtual machine is started. The boot layer contains module java.base and is the only layer in the Java virtual machine with a module named "java.base". The modules in the boot layer are mapped to the bootstrap class loader and other class loaders that are built-in into the Java virtual machine. The boot layer will often be the parent when creating additional layers. 

On (2), it's actually a DAG, not a tree :-)  But yes, you can definitely create multi-layer paths, which is why I talked about "parent or ancestral" layers.

On (3), fair enough -- I'm trying to avoid making the ClassGraph API any more complicated, but I think it makes sense to add this call. You'll find `ClassGraph#ignoreParentModuleLayers()` in master. Please let me know if this works for you, along with `ClassGraph#addModuleLayer(ModuleLayer)`.

**Comment by PavelTurk** [comment]
@lukehutch On (1) This is the code:

```
        for (Module m : ModuleLayer.boot().modules()) {
            System.out.println("Module from boot layer:" + m.getName());
        }
```
This is the output with my comments:

```
Module from boot layer:jdk.javaws
Module from boot layer:jdk.internal.opt
Module from boot layer:jdk.snmp
Module from boot layer:jdk.accessibility
Module from boot layer:java.scripting
Module from boot layer:me.pavelk.warmodulefinder   <!--FROM MODULE PATH -->
Module from boot layer:jdk.jshell
Module from boot layer:javafx.swing
Module from boot layer:jdk.localedata
Module from boot layer:jdk.jdeps
Module from boot layer:java.xml
Module from boot layer:jdk.packager
Module from boot layer:java.se
Module from boot layer:java.rmi
Module from boot layer:javafx.fxml
Module from boot layer:java.instrument
Module from boot layer:jdk.sctp
Module from boot layer:jdk.zipfs
Module from boot layer:jdk.internal.le
Module from boot layer:me.pavelk.kit.core  <!--FROM MODULE PATH -->
Module from boot layer:jdk.javadoc
Module from boot layer:jdk.jfr
Module from boot layer:jdk.xml.dom
Module from boot layer:jdk.jsobject
Module from boot layer:java.jnlp
Module from boot layer:java.compiler
Module from boot layer:jdk.editpad
Module from boot layer:me.pavelk.kit.jpms <!--FROM MODULE PATH -->
Module from boot layer:jdk.compiler
Module from boot layer:oracle.desktop
Module from boot layer:java.base
Module from boot layer:java.logging
Module from boot layer:jdk.security.auth
Module from boot layer:java.naming
Module from boot layer:java.sql
Module from boot layer:javafx.graphics
Module from boot layer:java.desktop
Module from boot layer:javafx.media
Module from boot layer:java.management.rmi
Module from boot layer:jdk.plugin.dom
Module from boot layer:javafx.web
Module from boot layer:jdk.net
Module from boot layer:jdk.management.resource
Module from boot layer:me.pavelk.alpha.core <!--FROM MODULE PATH -->
Module from boot layer:jdk.attach
Module from boot layer:java.security.jgss
Module from boot layer:java.prefs
Module from boot layer:jdk.jdi
Module from boot layer:jdk.httpserver
Module from boot layer:jdk.naming.dns
Module from boot layer:jdk.jconsole
Module from boot layer:jdk.plugin
Module from boot layer:slf4j.api <!--FROM MODULE PATH -->
Module from boot layer:slf4.simple <!--FROM MODULE PATH -->
Module from boot layer:jdk.packager.services
Module from boot layer:jdk.crypto.ec
Module from boot layer:jdk.management.agent
Module from boot layer:java.datatransfer
Module from boot layer:java.management
Module from boot layer:jdk.management.cmm
Module from boot layer:jdk.naming.rmi
Module from boot layer:jdk.jdwp.agent
Module from boot layer:java.xml.crypto
Module from boot layer:jdk.charsets
Module from boot layer:jdk.jlink
Module from boot layer:java.smartcardio
Module from boot layer:javafx.controls
Module from boot layer:jdk.dynalink
Module from boot layer:jdk.management
Module from boot layer:jdk.deploy
Module from boot layer:jdk.jartool
Module from boot layer:jdk.management.jfr
Module from boot layer:javafx.base
Module from boot layer:jdk.jstatd
Module from boot layer:jdk.crypto.cryptoki
Module from boot layer:jdk.unsupported
Module from boot layer:java.security.sasl
Module from boot layer:java.sql.rowset
Module from boot layer:oracle.net
Module from boot layer:jdk.security.jgss
Module from boot layer:jdk.internal.ed
Module from boot layer:jdk.scripting.nashorn
Module from boot layer:jdk.internal.jvmstat

```
As you see boot layer contains modules from module path.

**Comment by lukehutch** [comment]
Huh, interesting, thanks for showing the example. In JDK8 and before, I'm pretty sure the bootstrap classloader only ever loaded system classes (from `rt.jar`).

**Comment by PavelTurk** [comment]
@lukehutch On (3) this is my code

```
       //FRAGMENT 1
        try (ScanResult scanResult = new ClassGraph().scan()) {
            scanResult
                .getResourcesWithExtension("MF")
                .forEach((Resource res) -> {
                    System.out.println("Found 1 :" + res.getURL());
                });
        }
        //FRAGMENT 2
        try (ScanResult scanResult = new ClassGraph()
                .ignoreParentModuleLayers().scan()) {
            scanResult
                .getResourcesWithExtension("MF")
                .forEach((Resource res) -> {
                    System.out.println("Found 2 :" + res.getURL());
                });
        }
```
Fragment 1 shows manifests of modules of this layer and this layer parent. Fragment 2 shows manifests of the modules only of this layer (without the modules of the parent layer). So that's ok.

**Comment by lukehutch** [comment]
@PashaTurok thanks for testing. Pushed out as 4.2.2. I'll close this now, as this issue has served its purpose. Feel free to ping me on the ClassGraph gitter page, or file a bug in the ClassGraph issue tracker, if you require further assistance. Good luck!
